language: perl
matrix:
    fast_finish: true
before_install:
  - cpanm -n ExtUtils::MakeMaker
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.18"
  - "5.20"
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - cpanm -n --installdeps .
script:
    perl Makefile.PL && PERL5OPT=-MDevel::Cover make test
after_success:
    - cover -report codecov
